name: CMake

on:
  push:
    branches: [ move-volume-keys ]
  pull_request:
    branches: [ move-volume-keys ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Build leveldb
      run: |
        mkdir -p $HOME/src/builds
        pushd $HOME/src/builds
        git clone --recurse-submodules https://github.com/google/leveldb.git
        mkdir -p leveldb/build && cd leveldb/build
        cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
        popd

    - uses: actions/checkout@v2
    - uses: eWaterCycle/setup-grpc@v4
      with:
        grpc-version: 1.43.0

    - name: Build
      run: bash build.sh DT

    - name: Test
      run: |
        pushd tests
        bash test.sh
        popd
